apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8strustedrepos
spec:
  crd:
    spec:
      names:
        kind: K8sTrustedRepos
      validation:
        # Schema for the `parameters` field
        openAPIV3Schema:
          properties:
            repos:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8strustedrepos

        # For Pods
        violation[{"msg": msg}] {
          c := containers[_]
          satisfied := [good | repo = input.parameters.repos[_] ; good = startswith(c.image, repo)]
          not any(satisfied)
          msg := sprintf("container <%v> has an invalid image repo <%v>, allowed repos are %v", [c.name, c.image, input.parameters.repos])
        }

        # For Pod Containers
        containers[c] {
          c := input.review.object.spec.containers[_]
        }

        # For Pod InitContainers
        containers[c] {
          c := input.review.object.spec.initContainers[_]
        }

        # For Templated Pod Containers
        containers[c] {
          c := input.review.object.spec.template.spec.containers[_]
        }

        # For Templated Pod InitContainers
        containers[c] {
          c := input.review.object.spec.template.spec.initContainers[_]
        }
