apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sTrustedRepos
metadata:
  name: trusted-repos
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
      - apiGroups: ["apps"]
        kinds: ["Deployment"]
    namespaces:
      - "opa-example-app"
  parameters:
    repos:
      - "quay.io"
