---
# The opa-example-app-trigger Pipeline will run through several tasks:
# - source is pulled from git
# - deploy manifests via dry-run to test that OPA policy passes before moving on
# - conditions say go test must pass before moving on
# - source is built into an image by img
# - image output is pushed to ECR
# - cloudevent emitted
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: opa-example-app-trigger-pipeline
  namespace: opa-example-app-trigger
spec:
  resources:
    - name: source-repo
      type: git
    - name: image-source
      type: image
    - name: event-to-sink
      type: cloudEvent
  tasks:
    - name: apply-opa-policy
      taskRef:
        name: deploy-locally-dry-run
      resources:
        inputs:
          - name: source
            resource: source-repo
        outputs:
          - name: event-to-sink
            resource: event-to-sink
      params:
        - name: path
          value: /workspace/source/config/ocp/ #configure: may change according to your source
    - name: build-and-push-image
      taskRef:
        name: build-and-push-image
      runAfter:
        - apply-opa-policy
      conditions:
      - conditionRef: "go-test"
        resources:
          - name: source-repo
            resource: source-repo
      params:
        - name: PATH_CONTEXT
          value: /workspace/source
      resources:
        inputs:
          - name: source
            resource: source-repo
        outputs:
          - name: image
            resource: image-source
    - name: deploy-locally
      taskRef:
        name: deploy-locally
      runAfter:
        - build-and-push-image
      resources:
        inputs:
          - name: source
            resource: source-repo
        outputs:
          - name: event-to-sink
            resource: event-to-sink
      params:
        - name: path
          value: /workspace/source/config/ocp/ #configure: may change according to your source
---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: deploy-locally-dry-run
  namespace: opa-example-app-trigger
spec:
  resources:
    inputs:
      - name: source
        type: git
    outputs:
      - name: event-to-sink
        type: cloudEvent
  params:
    - name: path
      type: string
      description: Path to the manifests to apply
  steps:
    - name: run-oc
      image: quay.io/openshift/origin-cli:4.3
      command: ["oc"]
      args:
        - "apply"
        - "-f"
        - "$(params.path)"
        - "--server-dry-run"
