apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: opa-example-app-trigger-triggertemplate
  namespace: opa-example-app-trigger
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
    - name: namespace
      description: The namespace to create the resources
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: opa-example-app-trigger-pipeline-run-$(uid)
        namespace: $(params.namespace)
      spec:
        serviceAccountName: tekton-triggers-admin
        pipelineRef:
          name: opa-example-app-trigger-pipeline
        resources:
          - name: source-repo
            resourceSpec:
              type: git
              params:
              - name: revision
                value: $(params.gitrevision)
              - name: url
                value: $(params.gitrepositoryurl)
          - name: image-source
            resourceSpec:
              type: image
              params:
                - name: url
                  value: quay.io/ifont/opa-example-app # docker-repo-location.com/repo:opa-example-app-trigger
          - name: event-to-sink
            resourceSpec:
              type: cloudEvent
              params:
                - name: targetURI
                  value: http://event-display.opa-example-app-trigger.svc.cluster.local
---
apiVersion: tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: opa-example-app-trigger-pipelinebinding
  namespace: opa-example-app-trigger
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: namespace
      value: opa-example-app-trigger
    - name: gitrepositoryurl
      value: "https://github.com/$(body.repository.full_name)"
---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: opa-example-app-trigger-listener
  namespace: opa-example-app-trigger
spec:
  serviceAccountName: tekton-triggers-admin
  triggers:
    - bindings:
      - name: opa-example-app-trigger-pipelinebinding
      template:
        name: opa-example-app-trigger-triggertemplate
