apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: create-webhook-run
  namespace: getting-started
spec:
  taskRef:
    name: create-webhook
  inputs:
    params:
    - name: GitHubOrg
      value: "font"
    - name: GitHubUser
      value: "font"
    - name: GitHubRepo
      value: "opa-example-app"
    - name: GitHubSecretName
      value: webhook-secret
    - name: GitHubAccessTokenKey
      value: token
    - name: GitHubSecretStringKey
      value: secret
    - name: ExternalDomain
      value: triggers.ifontlabs.com
  timeout: 1000s
  serviceAccountName: tekton-triggers-createwebhook
